import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { pageMetadata } from "@/lib/seo/metadata";

export const dynamic = "force-dynamic";

export const metadata = pageMetadata({
  title: "Affiliate Program Terms",
  description: "The terms of the Crazy Chess Battles affiliate program.",
  path: "/affiliate/terms",
  noIndex: true,
});

const SECTIONS: { title: string; body: string[] }[] = [
  {
    title: "1. The program",
    body: [
      "As an affiliate you earn a 25% commission on platform fees generated by players who sign up through your referral link. Commissions are credited to your Crazy Chess Battles wallet automatically and instantly, every time the referred player pays.",
    ],
  },
  {
    title: "2. What earns commission",
    body: [
      "Every fee the referred player generates: cash battle fees, paid tournament entries, membership purchases and renewals, and ad placements. The commission is paid out of the platform's share — referred players never pay more for signing up through your link.",
    ],
  },
  {
    title: "3. Linking & activation",
    body: [
      "A referral is recorded once, at the moment a brand-new player signs up through your link. Each player is permanently linked to one referrer only. A referral starts as pending and becomes active when the friend makes their first paid move (usually a membership purchase).",
    ],
  },
  {
    title: "4. Duration",
    body: [
      "Commissions have no expiry. As long as your referred players keep generating fees, you keep earning — recurring on every membership renewal and every paid game they play.",
    ],
  },
  {
    title: "5. Fair play",
    body: [
      "Self-referrals, duplicate accounts, and any attempt to generate artificial fees are prohibited and void all associated commissions. Every commission is tied to a genuine payment. Accounts found abusing the program may lose affiliate privileges and unpaid commissions.",
    ],
  },
  {
    title: "6. Payouts",
    body: [
      "Commissions are paid to your wallet immediately — no payout requests or waiting periods. You can spend or withdraw your wallet balance at any time using the wallet's normal withdrawal options.",
    ],
  },
  {
    title: "7. Program changes",
    body: [
      "The platform may pause the program or adjust the commission rate for new referrals going forward. Anything already credited to your wallet stays yours. If the program is paused, referral links keep tracking sign-ups so no referral is lost while payouts wait.",
    ],
  },
  {
    title: "8. Your link",
    body: [
      "Your referral link is yours to share anywhere it's welcome. Don't spam: mass unsolicited messaging harms the community and your account. Keep it fun, keep it chess.",
    ],
  },
];

export default async function AffiliateTermsPage() {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) redirect("/login?redirect=/affiliate/terms");

  return (
    <div className="space-y-4">
      <div className="bg-ccb-card border border-ccb-border rounded-2xl p-4 sm:p-6">
        <h1 className="text-lg sm:text-xl font-extrabold">Affiliate program terms</h1>
        <p className="text-xs text-ccb-muted mt-1">
          The simple, honest rules of earning with your referral link.
        </p>
      </div>

      <div className="bg-ccb-card border border-ccb-border rounded-2xl p-4 sm:p-6 space-y-5">
        {SECTIONS.map((s) => (
          <div key={s.title}>
            <h2 className="text-sm font-bold mb-1.5">{s.title}</h2>
            {s.body.map((p, i) => (
              <p key={i} className="text-xs text-ccb-muted leading-relaxed">
                {p}
              </p>
            ))}
          </div>
        ))}
      </div>

      <p className="text-[11px] text-ccb-muted text-center">
        Questions about any of this? Reach out from the settings page — we answer fast.
      </p>
    </div>
  );
}
